#!/bin/sh
xrandr --dpi 290 --output eDP-1 --mode 3840x2400 --rotate normal --right-of DP-3-3 \
 --output DP-3-3 --mode 1920x1080 --rotate normal --right-of DP-3-2 \
 --output DP-3-2 --mode 1920x1080 --rotate normal --primary 
